title: Stupied OCs
description: >- # this means to ignore newlines until "baseurl:"
  Archive of all my ocs :3
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stupied-ocs.neocities.org"
github_username:  stupiedidiot

# Build settings
source: public
theme: minima
plugins:
  - jekyll-feed
