title: Stupied OCs
description: >- # this means to ignore newlines until "baseurl:"
  Archive of all my ocs :3
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stupied-ocs.neocities.org"
github_username:  stupiedidiot

# Build settings
source: public
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier

collections:
  psych:
    output: true
  pepup:
    output: true
  eighty-four:
    output: true  
  gayme:
    output: true
  misc:
    output: true

defaults:
  - scope:
      path: "" # Replace with the actual path to your folder
    values:
      layout: "page"      # Example: set a default layout